### ISSUE TITLE
Unbuffered stdout incompatible with Python 3

### ISSUE THREAD

**Issue by molinav** [molinav/gsync#3]
This is the traceback if I force to run `gsync` with Python 3:

```
vic@onyx:~/github/python-gsync$ python3 bin/gsync
Traceback (most recent call last):
  File "bin/gsync", line 19, in <module>
    from libgsync.output import verbose, debug, critical
  File "/home/vic/github/python-gsync/libgsync/output.py", line 20, in <module>
    sys.stdout = WRITER(os.fdopen(sys.stdout.fileno(), "w", 0), "replace")
  File "/usr/lib/python3.8/os.py", line 1023, in fdopen
    return io.open(fd, *args, **kwargs)
ValueError: can't have unbuffered text I/O
```

**Comment by molinav** [comment]
Maybe an implementation like [this one](https://stackoverflow.com/questions/107705/disable-output-buffering) from StackOverflow might help.

**Comment by molinav** [comment]
For the moment, it seems that forcing the opening mode of `sys.stdout` to `"wb"` instead of `"w"` does the trick for Python 3 without breaking for Python 2. Now I get another error but due to `GsyncOptions`:
```
vic@onyx:~/github/python-gsync$ python3 bin/gsync --help
Traceback (most recent call last):
  File "bin/gsync", line 97, in <module>
    sys.exit(main())
  File "bin/gsync", line 39, in main
    if GsyncOptions.verbose:
AttributeError: type object 'GsyncOptions' has no attribute 'verbose'
```
